const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0A84FF",
    background: "#F2F2F7",
    foreground: "#1C1C1E",
    card: "#FFFFFF",
    cardForeground: "#1C1C1E",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#E5E5EA",
    secondaryForeground: "#3A3A3C",
    muted: "#E5E5EA",
    mutedForeground: "#8E8E93",
    accent: "#30D158",
    accentForeground: "#FFFFFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#C6C6C8",
    input: "#E5E5EA",
    jarvisBlue: "#0A84FF",
    jarvisPulse: "#5AC8FA",
    userBubble: "#0A84FF",
    aiBubble: "#FFFFFF",
    overlay: "rgba(0,0,0,0.4)",
  },
  dark: {
    text: "#F2F2F7",
    tint: "#0A84FF",
    background: "#000000",
    foreground: "#F2F2F7",
    card: "#1C1C1E",
    cardForeground: "#F2F2F7",
    primary: "#0A84FF",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#30D158",
    accentForeground: "#FFFFFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#2C2C2E",
    jarvisBlue: "#0A84FF",
    jarvisPulse: "#5AC8FA",
    userBubble: "#0A84FF",
    aiBubble: "#2C2C2E",
    overlay: "rgba(0,0,0,0.6)",
  },
  radius: 14,
};

export default colors;
